const $=s=>document.querySelector(s); const KEY='dinkally_court_booking_v3', RATE=300, MAX_HOURS=8;
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{reservations:[],myBookings:[]}; let selected=[];
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
function localISO(d=new Date()){let z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,10)}
function showBooking(){$('#myView').classList.add('hidden');$('#bookingView').classList.remove('hidden');renderGrid()} function showMy(){$('#bookingView').classList.add('hidden');$('#myView').classList.remove('hidden');renderMy()} window.showBooking=showBooking;window.showMy=showMy;
function slots(){let a=[];for(let h=8;h<24;h++)a.push(h);for(let h=0;h<5;h++)a.push(h);return a}
function label(h){let suffix=h>=12?'PM':'AM',n=h%12||12;return `${n}:00 ${suffix}`}
function endLabel(h){return label((h+1)%24)}
function keyFor(h){return `${$('#bookingDate').value}|${h}`}
function reserved(h){return db.reservations.some(r=>r.key===keyFor(h)&&r.status==='paid')}
function renderGrid(){let date=$('#bookingDate').value;if(!date)return;$('#sessionGrid').innerHTML='<div class="gridHead courtHead"><div>TIME</div><div>COURT RATE</div><div>STATUS</div></div>'+slots().map(h=>{let r=reserved(h),sel=selected.includes(h);return `<div class="sessionRow courtRow"><div><b>${label(h)}</b><small>${endLabel(h)}</small></div><div><button class="slotBtn ${r?'full':''} ${sel?'selected':''}" ${r?'disabled':''} onclick="toggleSlot(${h})">${r?'Reserved':'PHP 300'}<br><small>${r?'Paid & confirmed':sel?'✓ Selected':'Click to select'}</small></button></div><div><span class="tag ${r?'reservedTag':''}">${r?'RESERVED':sel?'SELECTED':'AVAILABLE'}</span></div></div>`}).join('');renderSummary()}
function toggleSlot(h){if(reserved(h))return;if(selected.includes(h))selected=selected.filter(x=>x!==h);else{if(selected.length>=MAX_HOURS){alert('You can select a maximum of 8 hours.');return}selected.push(h)}selected.sort((a,b)=>slots().indexOf(a)-slots().indexOf(b));renderGrid()} window.toggleSlot=toggleSlot;
function renderSummary(){let b=$('#summaryBody');if(!selected.length){b.innerHTML='<div class="emptyCourt">🏓<br><b>No time selected</b><span>Select 1 to 8 available hourly slots.</span></div>';return}let total=selected.length*RATE;b.innerHTML=`<div class="summaryLine"><span>Date</span><b>${new Date($('#bookingDate').value+'T00:00').toLocaleDateString('en-PH',{month:'short',day:'numeric',year:'numeric'})}</b></div><div class="summaryLine"><span>Hours selected</span><b>${selected.length}</b></div><div class="chosenSlots">${selected.map(h=>`<div><span>${label(h)} – ${endLabel(h)}</span><b>₱300</b></div>`).join('')}</div><div class="summaryLine"><span>Court Rental</span><b>₱${total.toLocaleString()}</b></div><div class="summaryLine total"><span>Total</span><b>₱${total.toLocaleString()}</b></div><button class="primary wide" onclick="proceedPayment()">PROCEED TO PAYMENT</button><p class="holdNote">Selected slots become Reserved only after successful payment.</p>`}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')} function closeModal(){$('#modal').classList.add('hidden')} window.closeModal=closeModal;
function proceedPayment(){if(selected.length<1||selected.length>8)return;let date=$('#bookingDate').value,total=selected.length*RATE;openModal(`<h2>Proceed to Payment</h2><p class="meta">Dink-Ally Sports Center<br>${new Date(date+'T00:00').toLocaleDateString('en-PH',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</p><div class="chosenSlots">${selected.map(h=>`<div><span>${label(h)} – ${endLabel(h)}</span><b>₱300</b></div>`).join('')}</div><div class="summaryLine total"><span>Amount Due</span><b>₱${total.toLocaleString()}</b></div><label>Customer name *</label><input id="payName" placeholder="Full name"><label>Mobile number *</label><input id="payPhone" placeholder="09XX XXX XXXX"><div class="paymentBox"><b>Payment Gateway</b><p>This GitHub demo is payment-ready. Connect your live payment provider here before accepting real payments.</p></div><button class="primary wide" onclick="demoPaid()">SIMULATE SUCCESSFUL PAYMENT</button>`)} window.proceedPayment=proceedPayment;
function demoPaid(){let name=$('#payName').value.trim(),phone=$('#payPhone').value.trim();if(!name||!phone){alert('Please enter your name and mobile number.');return}let date=$('#bookingDate').value;if(selected.some(reserved)){alert('One of these slots has already been reserved. Please choose again.');closeModal();selected=[];renderGrid();return}let code='DA-'+Math.random().toString(36).slice(2,8).toUpperCase(),booking={id:code,date,hours:[...selected],name,phone,total:selected.length*RATE,status:'Paid',created:Date.now()};selected.forEach(h=>db.reservations.push({key:`${date}|${h}`,bookingId:code,status:'paid'}));db.myBookings.unshift(booking);save();selected=[];openModal(`<h2>Payment Successful ✓</h2><p>Your court booking is confirmed.</p><div class="bookingCode">${code}</div><p class="meta">The selected date and time slots are now marked <b>Reserved</b>.</p><button class="primary wide" onclick="closeModal();showMy()">VIEW MY BOOKING</button>`);renderGrid()} window.demoPaid=demoPaid;
function renderMy(){let a=db.myBookings;if(!a.length){$('#myBooking').innerHTML='<div class="card"><h3>No bookings on this device yet.</h3><p class="meta">Your paid reservations will appear here.</p><button class="primary" onclick="showBooking()">Book a Court</button></div>';return}$('#myBooking').innerHTML=a.map(b=>`<div class="card"><span class="pill">${b.status}</span><h3>Dink-Ally Court Reservation</h3><div class="bookingCode">${b.id}</div><div class="meta">👤 ${b.name}<br>📅 ${new Date(b.date+'T00:00').toLocaleDateString('en-PH',{month:'long',day:'numeric',year:'numeric'})}<br>🕒 ${b.hours.map(h=>label(h)+'–'+endLabel(h)).join(', ')}<br>💳 ₱${b.total.toLocaleString()}</div></div>`).join('')}
$('#bookingDate').min=localISO();$('#bookingDate').value=localISO();$('#bookingDate').addEventListener('change',()=>{selected=[];renderGrid()});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');renderGrid();
