const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s); const KEY='pickle_open_play_v1';
const seed={events:[{id:'op1',title:'Saturday Night Open Play',date:'2026-09-26',start:'20:00',end:'23:00',venue:'Dink-Ally Sports Center, San Miguel, Cordova, Cebu',level:'All Levels',max:24,fee:'150',notes:'Official Dink-Ally open play. Bring your paddle and water.',bookings:[]},{id:'op2',title:'Sunday Social Open Play',date:'2026-09-27',start:'20:00',end:'23:00',venue:'Dink-Ally Sports Center, San Miguel, Cordova, Cebu',level:'All Levels',max:24,fee:'150',notes:'Social open play for all levels.',bookings:[]}],myBooking:null};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||seed; const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
function hideAll(){['homeView','scheduleView','myView','adminView'].forEach(x=>$('#'+x).classList.add('hidden'))} function showHome(){hideAll();$('#homeView').classList.remove('hidden');renderEvents()} function showAdmin(){hideAll();$('#adminView').classList.remove('hidden');renderAdmin()} function showMy(){hideAll();$('#myView').classList.remove('hidden');renderMy()} function showSchedule(){hideAll();$('#scheduleView').classList.remove('hidden');renderSchedule()} window.showHome=showHome;window.showAdmin=showAdmin;window.showMy=showMy;window.showSchedule=showSchedule;
function fmtDate(s){return new Date(s+'T00:00:00').toLocaleDateString('en-PH',{weekday:'short',month:'short',day:'numeric',year:'numeric'})} function money(v){return !v||+v===0?'FREE':'₱'+v}
function eventCard(e,admin=false){let n=e.bookings.length,p=Math.min(100,n/e.max*100),left=Math.max(0,e.max-n);return `<article class="card"><div class="row between"><span class="pill">${e.level}</span><span class="tag">${left?left+' slots left':'WAITLIST'}</span></div><h3>${esc(e.title)}</h3><div class="meta">📅 ${fmtDate(e.date)} · ${e.start}–${e.end}<br>📍 ${esc(e.venue)}<br>💳 ${money(e.fee)}</div><div class="capacity"><div class="row between"><b>${n} / ${e.max} booked</b><small>${Math.round(p)}%</small></div><div class="bar"><i style="width:${p}%"></i></div></div>${admin?`<div class="row"><button class="primary" onclick="manageEvent('${e.id}')">Manage</button><button class="ghost" onclick="editEvent('${e.id}')">Edit</button><button class="danger" onclick="deleteEvent('${e.id}')">Delete</button></div>`:`<button class="primary wide" onclick="bookEvent('${e.id}')">${left?'BOOK A SLOT':'JOIN WAITLIST'}</button>`}</article>`}
function renderEvents(){let q=$('#search').value.toLowerCase(),l=$('#levelFilter').value;let a=db.events.filter(e=>(e.title+' '+e.venue).toLowerCase().includes(q)&&(!l||e.level===l));$('#events').innerHTML=a.length?a.map(e=>eventCard(e)).join(''):'<div class="card">No matching open plays yet.</div>'}

function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')} function closeModal(){$('#modal').classList.add('hidden')} window.closeModal=closeModal;
function bookEvent(id){let e=db.events.find(x=>x.id===id),full=e.bookings.length>=e.max;openModal(`<h2>${full?'Join Waitlist':'Reserve Your Slot'}</h2><p class="meta">${esc(e.title)} · ${fmtDate(e.date)} · ${e.start}<br>${esc(e.venue)}</p><form id="bookForm"><label>Player name *</label><input name="name" required placeholder="Juan Dela Cruz"><div class="grid2"><div><label>Contact number *</label><input name="contact" required placeholder="09XX XXX XXXX"></div><div><label>Club</label><input name="club" placeholder="e.g. Picklebeer"></div></div><label>Skill level</label><select name="level"><option>Beginner</option><option selected>Intermediate</option><option>Advanced</option></select><label>Notes (optional)</label><textarea name="notes" placeholder="Partner request, arrival note, etc."></textarea><button class="primary wide">${full?'JOIN WAITLIST':'CONFIRM BOOKING'}</button></form>`);$('#bookForm').onsubmit=x=>{x.preventDefault();let f=new FormData(x.target),code='PB-'+Math.random().toString(36).slice(2,7).toUpperCase(),b={id:crypto.randomUUID?.()||Date.now()+'',code,name:f.get('name'),contact:f.get('contact'),club:f.get('club'),level:f.get('level'),notes:f.get('notes'),status:full?'Waitlisted':'Confirmed',created:Date.now()};e.bookings.push(b);db.myBooking={eventId:e.id,bookingId:b.id};save();openModal(`<h2>${full?'Waitlist Added':'You’re In! 🎉'}</h2><p>Your booking code</p><div class="bookingCode">${code}</div><p><b>${esc(b.name)}</b><br>${esc(e.title)}<br>${fmtDate(e.date)} · ${e.start}<br><span class="pill">${b.status}</span></p><button class="primary wide" onclick="closeModal();showMy()">VIEW MY BOOKING</button>`);renderEvents()}}
window.bookEvent=bookEvent;
function renderMy(){let m=db.myBooking;if(!m){$('#myBooking').innerHTML='<div class="card"><h3>No booking saved on this device.</h3><p class="meta">Book an Open Play and your latest reservation will appear here.</p><button class="primary" onclick="showHome()">Browse Open Plays</button></div>';return}let e=db.events.find(x=>x.id===m.eventId),b=e?.bookings.find(x=>x.id===m.bookingId);if(!e||!b){db.myBooking=null;save();return renderMy()}$('#myBooking').innerHTML=`<div class="card"><span class="pill">${b.status}</span><h3>${esc(e.title)}</h3><div class="bookingCode">${b.code}</div><div class="meta">👤 ${esc(b.name)} · ${esc(b.level)}<br>🏓 ${esc(b.club||'No club')}<br>📅 ${fmtDate(e.date)} · ${e.start}–${e.end}<br>📍 ${esc(e.venue)}</div><button class="danger wide" onclick="cancelMine()">Cancel Booking</button></div>`}
function cancelMine(){if(!confirm('Cancel this booking?'))return;let m=db.myBooking,e=db.events.find(x=>x.id===m.eventId);if(e)e.bookings=e.bookings.filter(x=>x.id!==m.bookingId);db.myBooking=null;save();renderMy()}window.cancelMine=cancelMine;
function renderAdmin(){let total=db.events.reduce((a,e)=>a+e.bookings.length,0),slots=db.events.reduce((a,e)=>a+e.max,0);$('#stats').innerHTML=`<div class="stat"><b>${db.events.length}</b><span>Open Plays</span></div><div class="stat"><b>${total}</b><span>Bookings</span></div><div class="stat"><b>${Math.max(0,slots-total)}</b><span>Slots Left</span></div>`;$('#adminEvents').innerHTML=db.events.map(e=>eventCard(e,true)).join('')||'<div class="card">Create your first Open Play.</div>'}
$('#newEventBtn').onclick=()=>eventForm();function eventForm(e){openModal(`<h2>${e?'Edit':'Create'} Open Play</h2><form id="eventForm"><label>Event name *</label><input name="title" required value="${attr(e?.title||'')}"><div class="grid2"><div><label>Date *</label><input type="date" name="date" required value="${e?.date||''}"></div><div><label>Skill level</label><select name="level">${['All Levels','Beginner','Intermediate','Advanced'].map(x=>`<option ${e?.level===x?'selected':''}>${x}</option>`).join('')}</select></div><div><label>Start</label><input type="time" name="start" value="${e?.start||'20:00'}"></div><div><label>End</label><input type="time" name="end" value="${e?.end||'23:00'}"></div></div><label>Venue</label><input name="venue" readonly value="Dink-Ally Sports Center, San Miguel, Cordova, Cebu"><div class="grid2"><div><label>Maximum players</label><input type="number" min="2" name="max" value="${e?.max||24}"></div><div><label>Fee (PHP)</label><input type="number" min="0" name="fee" value="${e?.fee||0}"></div></div><label>Notes</label><textarea name="notes">${esc(e?.notes||'')}</textarea><button class="primary wide">SAVE OPEN PLAY</button></form>`);$('#eventForm').onsubmit=x=>{x.preventDefault();let f=Object.fromEntries(new FormData(x.target));let data={...e,...f,max:+f.max,bookings:e?.bookings||[],id:e?.id||'op'+Date.now()};if(e)db.events[db.events.findIndex(x=>x.id===e.id)]=data;else db.events.unshift(data);save();closeModal();renderAdmin()}}
function editEvent(id){eventForm(db.events.find(x=>x.id===id))} function deleteEvent(id){if(confirm('Delete this Open Play and its bookings?')){db.events=db.events.filter(x=>x.id!==id);save();renderAdmin()}} window.editEvent=editEvent;window.deleteEvent=deleteEvent;
function manageEvent(id){let e=db.events.find(x=>x.id===id);openModal(`<h2>${esc(e.title)}</h2><p class="meta">${e.bookings.length}/${e.max} registered</p><div>${e.bookings.length?e.bookings.map((b,i)=>`<div class="player"><div><b>${i+1}. ${esc(b.name)}</b><br><small>${esc(b.club||'No club')} · ${esc(b.level)} · ${esc(b.contact)}</small></div><span class="tag">${b.status}</span></div>`).join(''):'<p class="meta">No players booked yet.</p>'}</div><button class="ghost wide" onclick="copyShare('${id}')">🔗 Copy Public Link</button>`)} window.manageEvent=manageEvent;
function copyShare(id){let u=location.href.split('#')[0]+'#event='+id;navigator.clipboard?.writeText(u);alert('Public link copied. When hosted on GitHub Pages, share this link with players.')}window.copyShare=copyShare;
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))} function attr(v=''){return esc(v)}
function renderSchedule(){let e=db.events[0];let rows=[['5:00 PM','Beginner Open Play','12 / 16','available'],['6:00 PM','Intermediate Open Play','16 / 16','full'],['7:00 PM','All Levels Open Play','18 / 24','available'],['8:00 PM',e?.title||'Open Play',(e?.bookings.length||0)+' / '+(e?.max||24),'available'],['9:00 PM','Advanced Open Play','14 / 16','available']];$('#sessionGrid').innerHTML='<div class="gridHead"><div>TIME</div><div>OPEN PLAY SESSION</div><div>PLAYERS</div><div>STATUS</div></div>'+rows.map((r,i)=>`<div class="sessionRow"><div><b>${r[0]}</b></div><div><button class="slotBtn ${r[3]==='full'?'full':''}" ${r[3]==='full'?'disabled':''} onclick="selectSession(${i})">${r[1]}<br><small>${r[3]==='full'?'Session full':'Tap to select'}</small></button></div><div>${r[2]}</div><div><span class="tag">${r[3]==='full'?'FULL':'AVAILABLE'}</span></div></div>`).join('')}
function selectSession(i){let names=['Beginner Open Play','Intermediate Open Play','All Levels Open Play',db.events[0]?.title||'Open Play','Advanced Open Play'],times=['17:00','18:00','19:00','20:00','21:00'];if(i===1)return;let e=db.events[0];$('#summaryBody').innerHTML=`<div class="summaryLine"><span>Venue</span><b>Dink-Ally Sports Center</b></div><div class="summaryLine"><span>Session</span><b>${names[i]}</b></div><div class="summaryLine"><span>Date</span><b>Sep 26, 2026</b></div><div class="summaryLine"><span>Time</span><b>${times[i]}</b></div><div class="summaryLine"><span>Player Fee</span><b>₱${e?.fee||150}</b></div><div class="summaryLine total"><span>Total</span><b>₱${e?.fee||150}</b></div><p class="muted">By continuing, you agree to follow Dink-Ally Sports Center house rules and open play etiquette.</p><button class="primary wide" onclick="bookEvent('op1')">PROCEED TO BOOK</button>`} window.selectSession=selectSession;
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');showHome();
